return {
  ["workshop-1378549454"]={
    configuration_options={
      ["MemSpikeFix:"]=false,
      MemSpikeFixmaster_override=true,
      ["MemSpikeFixworkshop-1079538195"]="default",
      ["MemSpikeFixworkshop-1595631294"]="default",
      ["MemSpikeFixworkshop-1898181913"]="default",
      ["MemSpikeFixworkshop-1932983865"]="default",
      ["MemSpikeFixworkshop-1974725370"]="default",
      ["MemSpikeFixworkshop-2012031749"]="default",
      ["MemSpikeFixworkshop-2021716143"]="default",
      ["MemSpikeFixworkshop-2021943702"]="default",
      ["MemSpikeFixworkshop-2032577827"]="default",
      ["MemSpikeFixworkshop-2048852282"]="default",
      ["MemSpikeFixworkshop-2074508776"]="default",
      ["MemSpikeFixworkshop-347079953"]="default",
      ["MemSpikeFixworkshop-351325790"]="default",
      ["MemSpikeFixworkshop-362175979"]="default",
      ["MemSpikeFixworkshop-365119238"]="default",
      ["MemSpikeFixworkshop-367546858"]="default",
      ["MemSpikeFixworkshop-375850593"]="default",
      ["MemSpikeFixworkshop-375859599"]="default",
      ["MemSpikeFixworkshop-376333686"]="default",
      ["MemSpikeFixworkshop-378160973"]="default",
      ["MemSpikeFixworkshop-380079744"]="default",
      ["MemSpikeFixworkshop-386087632"]="default",
      ["MemSpikeFixworkshop-388109833"]="default",
      ["MemSpikeFixworkshop-396026892"]="default",
      ["MemSpikeFixworkshop-409184357"]="default",
      ["MemSpikeFixworkshop-454781545"]="default",
      ["MemSpikeFixworkshop-458587300"]="default",
      ["MemSpikeFixworkshop-462434129"]="default",
      ["MemSpikeFixworkshop-485291255"]="default",
      ["MemSpikeFixworkshop-490153236"]="default",
      ["MemSpikeFixworkshop-501385076"]="default",
      ["MemSpikeFixworkshop-572538624"]="default",
      ["MemSpikeFixworkshop-623749604"]="default",
      ["MemSpikeFixworkshop-632082897"]="default",
      ["MemSpikeFixworkshop-661253977"]="default",
      ["MemSpikeFixworkshop-727774324"]="default",
      ["MemSpikeFixworkshop-758532836"]="default",
      ["MemSpikeFixworkshop-780009141"]="default",
      ["MemSpikeFixworkshop-801304958"]="default",
      ["MemSpikeFixworkshop-804549021"]="default",
      ["MemSpikeFixworkshop-812723897"]="default",
      ["MemSpikeFixworkshop-821143467"]="default",
      ["MemSpikeFixworkshop-829519717"]="default",
      ["MemSpikeFixworkshop-829521521"]="default",
      ["MemSpikeFixworkshop-831523966"]="default",
      ["MemSpikeFixworkshop-836583293"]="default",
      ["MemSpikeFixworkshop-842702425"]="default",
      ["MemSpikeFixworkshop-934638020"]="default",
      craftinghighlight=false 
    },
    enabled=true 
  },
  ["workshop-1595631294"]={
    configuration_options={
      BundleItems=false,
      ChangeSkin=true,
      Digornot=false,
      DragonflyChest=false,
      Icebox=false,
      SaltBox=false 
    },
    enabled=true 
  },
  ["workshop-1898181913"]={ configuration_options={  }, enabled=true },
  ["workshop-1932983865"]={ configuration_options={ RANGE=5, recipe_complexity="normal" }, enabled=true },
  ["workshop-1974725370"]={
    configuration_options={
      leastnum_beefalo=2,
      leastnum_beehive=2,
      leastnum_catcoonden=2,
      leastnum_knight=2,
      leastnum_lightninggoat=2,
      leastnum_rocky=2,
      leastnum_slurtlehole=2,
      leastnum_spiderden=2,
      respawnmechanism="scripts/respawnnear.lua",
      respawntime=5 
    },
    enabled=true 
  },
  ["workshop-2012031749"]={
    configuration_options={
      _DEVG_override=0,
      _HOUND_override=0,
      _IPIG_override=0,
      _LEIF_override=0,
      _MACC_override=0,
      _MACV_override=0,
      _MAXM_override=0,
      _MAXP_override=0,
      _OASISEXTRA_override=0,
      _OASIS_override=0,
      _PIGS_override=0,
      _POI_override=3,
      _PR_override=3,
      _REEDS_override=1,
      _SPIDER_override=0,
      _TALLB_override=0,
      _TR_override=1,
      banner1=false,
      banner2=false,
      banner3=false 
    },
    enabled=true 
  },
  ["workshop-2021716143"]={ configuration_options={ enable_attack_warning=true }, enabled=true },
  ["workshop-2021943702"]={ configuration_options={  }, enabled=true },
  ["workshop-2032577827"]={
    configuration_options={ activate_delay_mode=0, emergency_time=5, fuel_time=2, turn_on_time=1 },
    enabled=true 
  },
  ["workshop-2048852282"]={ configuration_options={  }, enabled=true },
  ["workshop-2074508776"]={
    configuration_options={ handmake=20, onlyclose=false, range=2.3 },
    enabled=true 
  },
  ["workshop-347079953"]={
    configuration_options={ DFV_Language="CN", DFV_MinimalMode="default" },
    enabled=true 
  },
  ["workshop-362175979"]={ configuration_options={ ["Draw over FoW"]="disabled" }, enabled=true },
  ["workshop-375850593"]={ configuration_options={  }, enabled=true },
  ["workshop-375859599"]={
    configuration_options={
      divider=5,
      random_health_value=0,
      random_range=0,
      send_unknwon_prefabs=false,
      show_type=0,
      unknwon_prefabs=1,
      use_blacklist=true 
    },
    enabled=true 
  },
  ["workshop-378160973"]={
    configuration_options={
      ENABLEPINGS=true,
      FIREOPTIONS=2,
      OVERRIDEMODE=false,
      SHAREMINIMAPPROGRESS=true,
      SHOWFIREICONS=true,
      SHOWPLAYERICONS=true,
      SHOWPLAYERSOPTIONS=2 
    },
    enabled=true 
  },
  ["workshop-396026892"]={ configuration_options={ OPT_DIFFICULTY=1 }, enabled=true },
  ["workshop-458587300"]={ configuration_options={ Ownership=false, Travel_Cost=32 }, enabled=true },
  ["workshop-462434129"]={
    configuration_options={
      MOD_RESTART_ALLOW_KILL=true,
      MOD_RESTART_ALLOW_RESTART=true,
      MOD_RESTART_ALLOW_RESURRECT=true,
      MOD_RESTART_CD_BONUS=0,
      MOD_RESTART_CD_KILL=3,
      MOD_RESTART_CD_MAX=0,
      MOD_RESTART_CD_RESTART=5,
      MOD_RESTART_CD_RESURRECT=7,
      MOD_RESTART_FORCE_DROP_MODE=0,
      MOD_RESTART_IGNORING_ADMIN=true,
      MOD_RESTART_MAP_SAVE=2,
      MOD_RESTART_RESURRECT_HEALTH=0,
      MOD_RESTART_TRIGGER_MODE=1,
      MOD_RESTART_WELCOME_TIPS=true,
      MOD_RESTART_WELCOME_TIPS_TIME=6 
    },
    enabled=true 
  },
  ["workshop-501385076"]={
    configuration_options={
      quick_cook_on_fire=true,
      quick_harvest=true,
      quick_pick_cactus=true,
      quick_pick_plant_normal_ground=true 
    },
    enabled=true 
  },
  ["workshop-623749604"]={
    configuration_options={
      Craft="Normal",
      Destroyable="DestroyByAll",
      FoodSpoilage=1,
      Language="TCh",
      Position="Center",
      Slots=80 
    },
    enabled=true 
  },
  ["workshop-661253977"]={
    configuration_options={ amudiao=true, baodiao=1, kong=0, nillots=0, rendiao=2, zbdiao=true },
    enabled=true 
  },
  ["workshop-758532836"]={
    configuration_options={
      AUTOPAUSECONSOLE=false,
      AUTOPAUSEMAP=false,
      AUTOPAUSESINGLEPLAYER=true,
      ENABLECLIENTPAUSING=false,
      ENABLEHOTKEY=false,
      KEYBOARDTOGGLEKEY="P" 
    },
    enabled=true 
  },
  ["workshop-801304958"]={
    configuration_options={ SHOWBUCKTIME=true, SHOWDELTADOMESTICATION=true, SHOWOBEDIENCE=false },
    enabled=true 
  },
  ["workshop-812723897"]={
    configuration_options={
      ITEMS="true",
      MISCELLANEOUS="true",
      MOBS="true",
      ["MOBS - GIANTS"]="true",
      ["MOBS - KOALEFANTS"]="true",
      ["MOBS - SHIPWRECKED"]="true",
      ["MOBS - SHIPWRECKED BOSSES"]="true",
      MUSHROOMS="true",
      STRUCTURES="true",
      ["STRUCTURES - WALLS"]="true",
      THINGS="true",
      VEGETATION="true",
      animal_track="true",
      babybeefalo="true",
      ballphin="true",
      bearger="true",
      beefalo="true",
      bishop="true",
      blue_mushroom="true",
      carrot_planted="true",
      chester_eyebone="true",
      crabhole="true",
      deerclops="true",
      doydoy="true",
      doydoybaby="true",
      dragonfly="true",
      flint="true",
      flotsam="true",
      green_mushroom="true",
      houndbone="true",
      knight="true",
      koalefant_summer="true",
      koalefant_winter="true",
      kraken="true",
      leif="true",
      leif_sparse="true",
      lightninggoat="true",
      mandrake="true",
      mermhead="true",
      molehill="true",
      moose="true",
      ox="true",
      packim_fishbone="true",
      pighead="true",
      pigtorch="true",
      rabbithole="true",
      red_mushroom="true",
      rocky="true",
      rook="true",
      sandbagsmall="true",
      skeleton="true",
      swordfish="true",
      teleportato_box="true",
      teleportato_crank="true",
      teleportato_potato="true",
      teleportato_ring="true",
      tentacle="true",
      tigershark="true",
      treeguard="true",
      twister="true",
      wall_hay="true",
      wall_limestone="true",
      wall_ruins="true",
      wall_stone="true",
      wall_wood="true",
      wildborehead="true" 
    },
    enabled=true 
  },
  ["workshop-829519717"]={ configuration_options={ Controller=false }, enabled=true },
  ["workshop-829521521"]={
    configuration_options={
      ["Horizontal Margin"]=235,
      ["Minimap Size"]=0.225,
      Position="top_right",
      ["Updates Per Second"]=0,
      ["Vertical Margin"]=25 
    },
    enabled=true 
  },
  ["workshop-831523966"]={ configuration_options={ soul_stack=20, stack_size=999 }, enabled=true },
  ["workshop-934638020"]={ configuration_options={  }, enabled=true } 
}